# Generated by Django 3.2.7 on 2021-09-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depoimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('foto', models.ImageField(upload_to='foto', verbose_name='Foto')),
                ('depoimento', models.CharField(max_length=250, verbose_name='Depoimento')),
            ],
        ),
        migrations.CreateModel(
            name='Redes_Sociais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=100, verbose_name='Facebook')),
                ('twitter', models.CharField(max_length=100, verbose_name='Twitter')),
                ('pinterest', models.CharField(max_length=100, verbose_name='Pinterest')),
                ('instagram', models.CharField(max_length=100, verbose_name='Instagram')),
            ],
        ),
    ]
